apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  template:
    metadata:
      name: jaeger
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.35
          imagePullPolicy: IfNotPresent
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: "9411"
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1000Mi"
              cpu: "500m"
      restartPolicy: Always
  selector:
    matchLabels:
      app: jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - port: 5775
      protocol: UDP
      name: "5775"
    - port: 6831
      protocol: UDP
      name: "6831"
    - port: 6832
      protocol: UDP
      name: "6832"
    - port: 5778
      protocol: TCP
      name: "5778"
    - port: 16686
      protocol: TCP
      name: "16686"
    - port: 14268
      protocol: TCP
      name: "14268"
    - port: 14250
      protocol: TCP
      name: "14250"
    - port: 9411
      protocol: TCP
      name: "9411"
  type: NodePort