apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  template:
    metadata:
      name: kibana
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:8.3.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "512Mi"
              cpu: "300m"
            limits:
              memory: "1000Mi"
              cpu: "500m"
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elastic:9200
      restartPolicy: Always
  selector:
    matchLabels:
      app: kibana
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  selector:
    app: kibana
  ports:
    - port: 5601
      name: http
  type: NodePort
