apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  replicas: 3
  template:
    metadata:
      name: microservice
      labels:
        app: microservice
    spec:
      containers:
        - name: microservice
          image: alexanderbryksin/search_microservice:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: JAEGER_HOST_PORT
              value: jaeger:6831
            - name: ELASTIC_URL
              value: http://elastic:9200
            - name: RABBITMQ_URI
              value: amqp://guest:guest@rabbitmq:5672/
      restartPolicy: Always
  selector:
    matchLabels:
      app: microservice
---
apiVersion: v1
kind: Service
metadata:
  name: microservice
spec:
  selector:
    app: microservice
  ports:
    - name: microservice-port
      port: 8000
      protocol: TCP
  type: LoadBalancer
