apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  labels:
    app: microservice
spec:
  replicas: 1
  template:
    metadata:
      name: microservice
      labels:
        app: microservice
    spec:
      containers:
        - name: microservice
          image: alexanderbryksin/search_microservice:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "1000Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /live
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: JAEGER_HOST_PORT
              value: jaeger:6831
            - name: ELASTIC_URL
              value: http://elastic:9200
            - name: RABBITMQ_URI
              value: amqp://guest:guest@rabbitmq:5672/
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

  selector:
    matchLabels:
      app: microservice
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-service
spec:
  type: LoadBalancer
  selector:
    app: microservice
  ports:
    - name: microservice-port
      port: 8000
      protocol: TCP
    - name: microservice-metrics
      port: 3001
      protocol: TCP
      targetPort: 3001
