apiVersion: apps/v1
kind: Deployment
metadata:
  name: search_microservice
  labels:
    app: search_microservice
spec:
  replicas: 1
  template:
    metadata:
      name: search_microservice
      labels:
        app: search_microservice
    spec:
      containers:
        - name: search_microservice
          image: alexanderbryksin/search_microservice:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "300m"
            limits:
              memory: "1000Mi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /live
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8001
              name: metrics
            - containerPort: 3001
              name: healthcheck
          env:
            - name: JAEGER_HOST_PORT
              value: jaeger:6831
            - name: ELASTIC_URL
              value: http://elastic:9200
            - name: RABBITMQ_URI
              value: amqp://guest:guest@rabbitmq:5672/
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  selector:
    matchLabels:
      app: search_microservice
---
apiVersion: v1
kind: Service
metadata:
  name: search_microservice-service
  labels:
    app: search_microservice
spec:
  type: ClusterIP
  selector:
    app: search_microservice
  ports:
    - name: http
      port: 8000
      protocol: TCP
    - name: healthcheck
      port: 3001
      protocol: TCP
      targetPort: metrics
    - name: metrics
      port: 8001
      protocol: TCP
      targetPort: metrics
