apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: search
  name: search_microservice-service-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: search_microservice
  endpoints:
    - interval: 15s
      port: metrics
      path: /metrics