apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: monitoring
  name: search-microservice-service-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: search-microservice
  endpoints:
    - interval: 10s
      port: metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - default