serviceName: search_service
grpc:
  port: :5001
  development: true
http:
  port: :8000
  development: true
  basePath: /api/v1
  productsPath: /api/v1/products
  debugErrorsResponse: true
  ignoreLogUrls: [ "metrics", "swagger" ]
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8001
  checkIntervalSeconds: 10
logger:
  level: info
  devMode: false
  encoder: console
kafka:
  brokers: [ "localhost:9093" ]
  groupID: bank_account_microservice_consumer
  initTopics: true
kafkaTopics:
  eventCreated:
    topicName: event_created
    partitions: 10
    replicationFactor: 1
jaeger:
  enable: true
  serviceName: bank_account_service
  hostPort: "localhost:6831"
  logSpans: false
timeouts:
  postgresInitMilliseconds: 1500
  postgresInitRetryCount: 3
elasticSearch:
  addresses: ["http://localhost:9200"]
  username: ""
  password: ""
  apiKey: ""
  enableLogging: true
elasticIndexes:
  products:
    path: config/mappings.json
    name: products
    alias: products-alias
rabbitmq:
  uri: amqp://guest:guest@localhost:5672/
exchangeAndQueueBindings:
  indexProductBinding:
    exchangeName: products
    exchangeKind: direct
    queueName: index-product
    bindingKey: products-index
